### Get all articles
GET http://localhost:8000/api/articles?categories=2,4&page=1&per_page=10

### Get article by id
GET http://localhost:8000/api/articles/1

### Create article
POST http://localhost:8000/api/articles
Content-Type: application/json

{}

### Update article
PATCH http://localhost:8000/api/articles/1
Content-Type: application/json

{}

### Delete article
DELETE http://localhost:8000/api/articles/1
