### Get all categories
GET http://localhost:8000/api/categories

### Get category by id
GET http://localhost:8000/api/categories/1

### Create category
POST http://localhost:8000/api/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImF2YXRhciI6Imh0dHBzOi8vYXZhdGFycy5naXRodWJ1c2VyY29udGVudC5jb20vdS83ODA5MjYwOCIsImVtYWlsIjoiYWRtaW5AcXVpbGxxdWVzdC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCQwU21BRnZJMTR0Z3JCOW5nSXBHS1VPS2svY1laNjZTLklGOEg3UjRJWFZ3V3Y1dngucDF3YSIsInByb2Zlc3Npb24iOiJBdXRob3IiLCJyb2xlIjoiQURNSU4iLCJjcmVhdGVkQXQiOiIyMDIzLTA1LTE3VDEwOjU5OjE1LjMyNVoiLCJ1cGRhdGVkQXQiOiIyMDIzLTA1LTE3VDEwOjU5OjE1LjMyNVoiLCJpYXQiOjE2ODQ0MjY4NDYsImV4cCI6MTY4NDUxMzI0Nn0.Z3pmJ5UEpJw4f2hc-fm-jlcI5Y2o0zT_yUBRVbsi7yw

{
    "name": "Hello World"
}

### Update category
PATCH http://localhost:8000/api/categories/11
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImF2YXRhciI6Imh0dHBzOi8vYXZhdGFycy5naXRodWJ1c2VyY29udGVudC5jb20vdS83ODA5MjYwOCIsImVtYWlsIjoiYWRtaW5AcXVpbGxxdWVzdC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCQwU21BRnZJMTR0Z3JCOW5nSXBHS1VPS2svY1laNjZTLklGOEg3UjRJWFZ3V3Y1dngucDF3YSIsInByb2Zlc3Npb24iOiJBdXRob3IiLCJyb2xlIjoiQURNSU4iLCJjcmVhdGVkQXQiOiIyMDIzLTA1LTE3VDEwOjU5OjE1LjMyNVoiLCJ1cGRhdGVkQXQiOiIyMDIzLTA1LTE3VDEwOjU5OjE1LjMyNVoiLCJpYXQiOjE2ODQ0MjY4NDYsImV4cCI6MTY4NDUxMzI0Nn0.Z3pmJ5UEpJw4f2hc-fm-jlcI5Y2o0zT_yUBRVbsi7yw

{
    "name": "Hello World - Edited"
}

### Delete category
DELETE http://localhost:8000/api/categories/11
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImF2YXRhciI6Imh0dHBzOi8vYXZhdGFycy5naXRodWJ1c2VyY29udGVudC5jb20vdS83ODA5MjYwOCIsImVtYWlsIjoiYWRtaW5AcXVpbGxxdWVzdC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCQwU21BRnZJMTR0Z3JCOW5nSXBHS1VPS2svY1laNjZTLklGOEg3UjRJWFZ3V3Y1dngucDF3YSIsInByb2Zlc3Npb24iOiJBdXRob3IiLCJyb2xlIjoiQURNSU4iLCJjcmVhdGVkQXQiOiIyMDIzLTA1LTE3VDEwOjU5OjE1LjMyNVoiLCJ1cGRhdGVkQXQiOiIyMDIzLTA1LTE3VDEwOjU5OjE1LjMyNVoiLCJpYXQiOjE2ODQ0MjY4NDYsImV4cCI6MTY4NDUxMzI0Nn0.Z3pmJ5UEpJw4f2hc-fm-jlcI5Y2o0zT_yUBRVbsi7yw
