### Upload user avatar
POST http://localhost:8000/api/users/avatar
Content-Type: multipart/form-data; boundary=MyBoundary
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsInVzZXJuYW1lIjoiYnJhaGltIiwiYXZhdGFyIjpudWxsLCJlbWFpbCI6ImJyYWhpbS5lbGhvdWJlQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJENnaE1zMVdLQ3BqaDcxcVVvUGhMZWVCeGVKQTZTSjZIbU9JLmMxSWVpNFU3YmwwWWdWL2F5IiwicHJvZmVzc2lvbiI6IlRlc3RlciIsInJvbGUiOiJBVVRIT1IiLCJjcmVhdGVkQXQiOiIyMDIzLTA1LTIwVDE5OjE1OjU0Ljk2OFoiLCJ1cGRhdGVkQXQiOiIyMDIzLTA1LTIwVDE5OjE1OjU0Ljk2OFoiLCJfY291bnQiOnsiYXJ0aWNsZXMiOjB9LCJpYXQiOjE2ODQ2MTAxNzQsImV4cCI6MTY4NDY5NjU3NH0.sw9BYohhxBskGO9gl_oS1j55nzN4ZMY44zvlxeSvvvo

--MyBoundary
Content-Disposition: form-data; name="avatar"; filename="article.jpg"
Content-Type: image/jpeg

< ./files/avatar.jpg
--MyBoundary--

### Get article image
GET http://localhost:8000/api/users/avatar/1684626805225-yvroais85mm

### Change password
POST http://localhost:8000/api/users/update/password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsInVzZXJuYW1lIjoiYnJhaGltIiwiYXZhdGFyIjpudWxsLCJlbWFpbCI6ImJyYWhpbS5lbGhvdWJlQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJENnaE1zMVdLQ3BqaDcxcVVvUGhMZWVCeGVKQTZTSjZIbU9JLmMxSWVpNFU3YmwwWWdWL2F5IiwicHJvZmVzc2lvbiI6IlRlc3RlciIsInJvbGUiOiJBVVRIT1IiLCJjcmVhdGVkQXQiOiIyMDIzLTA1LTIwVDE5OjE1OjU0Ljk2OFoiLCJ1cGRhdGVkQXQiOiIyMDIzLTA1LTIwVDE5OjE1OjU0Ljk2OFoiLCJfY291bnQiOnsiYXJ0aWNsZXMiOjB9LCJpYXQiOjE2ODQ2MTAxNzQsImV4cCI6MTY4NDY5NjU3NH0.sw9BYohhxBskGO9gl_oS1j55nzN4ZMY44zvlxeSvvvo

{
    "oldPassword": "password",
    "password": "abcd1234"
}

### Update user data
POST http://localhost:8000/api/users/update/data
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsInVzZXJuYW1lIjoiYnJhaGltIiwiYXZhdGFyIjpudWxsLCJlbWFpbCI6ImJyYWhpbS5lbGhvdWJlQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJENnaE1zMVdLQ3BqaDcxcVVvUGhMZWVCeGVKQTZTSjZIbU9JLmMxSWVpNFU3YmwwWWdWL2F5IiwicHJvZmVzc2lvbiI6IlRlc3RlciIsInJvbGUiOiJBVVRIT1IiLCJjcmVhdGVkQXQiOiIyMDIzLTA1LTIwVDE5OjE1OjU0Ljk2OFoiLCJ1cGRhdGVkQXQiOiIyMDIzLTA1LTIwVDE5OjE1OjU0Ljk2OFoiLCJfY291bnQiOnsiYXJ0aWNsZXMiOjB9LCJpYXQiOjE2ODQ2MTAxNzQsImV4cCI6MTY4NDY5NjU3NH0.sw9BYohhxBskGO9gl_oS1j55nzN4ZMY44zvlxeSvvvo

{
    "username": "brahimell",
    "profession": "Developer"
}
